from app import Client
import sys 

num_servers = int(sys.argv[1])

servers = []
ports = [33330 + i for i in range(num_servers)]


#print("starting up clients...")
c = Client(ports)

c.set("jack", 22)
c.set("alice", 30)
c.set("bob", 45)
c.set("emma", 28)
c.set("john", 35)
c.set("sara", 18)
c.set("michael", 50)
c.set("lucy", 26)
c.set("david", 39)
c.set("olivia", 32)
c.set("peter", 42)
c.set("mary", 29)
c.set("alex", 33)
c.set("sophia", 24)
c.set("james", 37)
c.set("natalie", 27)
c.set("robert", 51)
c.set("grace", 23)
c.set("william", 38)
c.set("ana", 33)
c.set("mia", 31)
c.set("charlie", 19)
c.set("hannah", 34)
c.set("george", 48)
c.set("eva", 25)
c.set("thomas", 41)
c.set("victoria", 36)
c.set("andrew", 49)
c.set("emily", 21)
c.set("jacob", 43)
c.set("sophie", 30)
c.set("matthew", 44)
c.set("amelia", 20)
c.set("benjamin", 46)
c.set("lily", 22)
c.set("nathan", 40)
c.set("chloe", 31)
c.set("samuel", 47)
c.set("ella", 27)
c.set("liam", 52)
c.set("christopher", 54)
c.set("ava", 28)
c.set("daniel", 53)
c.set("ethan", 55)
c.set("scarlett", 24)
c.set("joshua", 56)
c.set("harper", 25)
c.set("zoe", 26)
c.set("christian", 59)
c.set("jackson", 60)
c.set("owen", 61)
c.set("isaac", 62)
c.set("luke", 63)
c.set("henry", 64)
c.set("max", 65)
c.set("austin", 67)
c.set("noah", 68)
c.set("levi", 69)
c.set("lucas", 70)
c.set("dylan", 71)
c.set("sebastian", 72)
c.set("charlotte", 73)
c.set("jayden", 74)
c.set("adam", 75)
c.set("wyatt", 76)
c.set("isaiah", 77)
c.set("gabriel", 78)
c.set("julian", 79)
c.set("leo", 80)
c.set("zoey", 81)



c.get("jack")
c.get("alice")
c.get("bob")
c.get("emma")
c.get("john")
c.get("sara")
c.get("michael")
c.get("lucy")
c.get("david")
c.get("olivia")
c.get("peter")
c.get("mary")
c.get("alex")
c.get("sophia")
c.get("james")
c.get("natalie")
c.get("robert")
c.get("grace")
c.get("william")
c.get("mia")
c.get("charlie")
c.get("hannah")
c.get("george")
c.get("eva")
c.get("thomas")
c.get("victoria")
c.get("andrew")
c.get("emily")
c.get("jacob")
c.get("sophie")
c.get("matthew")
c.get("amelia")
c.get("benjamin")
c.get("lily")
c.get("nathan")
c.get("chloe")
c.get("samuel")
c.get("ella")
c.get("liam")
c.get("christopher")
c.get("ava")
c.get("daniel")
c.get("ethan")
c.get("scarlett")
c.get("joshua")
c.get("harper")
c.get("zoe")
c.get("christian")
c.get("jackson")
c.get("owen")
c.get("isaac")
c.get("luke")
c.get("henry")
c.get("max")
c.get("austin")
c.get("noah")
c.get("levi")
c.get("lucas")
c.get("dylan")
c.get("sebastian")
c.get("charlotte")
c.get("jayden")
c.get("adam")
c.get("wyatt")
c.get("isaiah")
c.get("gabriel")
c.get("julian")
c.get("leo")
c.get("zoey")



print(f"num hits - {c.hits}, num misses - {c.misses}")
